apiVersion: apps/v1
kind: Deployment
metadata:
  name: pilates-reformer-admin
  namespace: pilates-reformer
  labels:
    app: pilates-reformer-admin
spec:
  replicas: 1

  selector:
    matchLabels:
      app: pilates-reformer-admin

  template:
    metadata:
      labels:
        app: pilates-reformer-admin
    spec:
      containers:
        - name: pilates-reformer-admin
          image: __IMAGE__
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 3000

          env:
            - name: NODE_OPTIONS
              value: --max-old-space-size=256

          envFrom:
            - secretRef:
                name: pilates-reformer-secrets
                optional: true
            - secretRef:
                name: postgres-credentials

          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 15

          resources:
            requests:
              cpu: 98m
              memory: 240Mi
            limits:
              cpu: 450m
              memory: 384Mi
