apiVersion: v1
kind: Service
metadata:
  name: pilates-reformer-admin
  namespace: pilates-reformer
  labels:
    app: pilates-reformer-admin
spec:
  type: NodePort

  selector:
    app: pilates-reformer-admin

  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 30082
